#! /bin/bash

cd /home/cesare/Projects/apriori-and-sons || exit 
mkdir -p /home/cesare/Projects/apriori-and-sons/result/logs || exit 
python /home/cesare/Projects/apriori-and-sons/main.py runtask son_apriori_25K40_10 son_apriori 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/25K40.txt /home/cesare/Projects/apriori-and-sons/result/son_apriori_25K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/son_apriori_25K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask son_apriori_100K40_10 son_apriori 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K40.txt /home/cesare/Projects/apriori-and-sons/result/son_apriori_100K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/son_apriori_100K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask son_apriori_retail_10 son_apriori 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/retail.txt /home/cesare/Projects/apriori-and-sons/result/son_apriori_retail_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/son_apriori_retail_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask son_apriori_100K10_10 son_apriori 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K10.txt /home/cesare/Projects/apriori-and-sons/result/son_apriori_100K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/son_apriori_100K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask son_apriori_50K10_10 son_apriori 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/50K10.txt /home/cesare/Projects/apriori-and-sons/result/son_apriori_50K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/son_apriori_50K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_25K40_10 pcy 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/25K40.txt /home/cesare/Projects/apriori-and-sons/result/pcy_25K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_25K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_100K40_10 pcy 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K40.txt /home/cesare/Projects/apriori-and-sons/result/pcy_100K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_100K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_retail_10 pcy 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/retail.txt /home/cesare/Projects/apriori-and-sons/result/pcy_retail_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_retail_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_100K10_10 pcy 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K10.txt /home/cesare/Projects/apriori-and-sons/result/pcy_100K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_100K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_50K10_10 pcy 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/50K10.txt /home/cesare/Projects/apriori-and-sons/result/pcy_50K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_50K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_erode_25K40_10 pcy_erode 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/25K40.txt /home/cesare/Projects/apriori-and-sons/result/pcy_erode_25K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_erode_25K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_erode_100K40_10 pcy_erode 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K40.txt /home/cesare/Projects/apriori-and-sons/result/pcy_erode_100K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_erode_100K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_erode_retail_10 pcy_erode 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/retail.txt /home/cesare/Projects/apriori-and-sons/result/pcy_erode_retail_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_erode_retail_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_erode_100K10_10 pcy_erode 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K10.txt /home/cesare/Projects/apriori-and-sons/result/pcy_erode_100K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_erode_100K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask pcy_erode_50K10_10 pcy_erode 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/50K10.txt /home/cesare/Projects/apriori-and-sons/result/pcy_erode_50K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/pcy_erode_50K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_python_25K40_10 apriori_python 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/25K40.txt /home/cesare/Projects/apriori-and-sons/result/apriori_python_25K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_python_25K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_python_100K40_10 apriori_python 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K40.txt /home/cesare/Projects/apriori-and-sons/result/apriori_python_100K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_python_100K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_python_retail_10 apriori_python 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/retail.txt /home/cesare/Projects/apriori-and-sons/result/apriori_python_retail_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_python_retail_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_python_100K10_10 apriori_python 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K10.txt /home/cesare/Projects/apriori-and-sons/result/apriori_python_100K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_python_100K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_python_50K10_10 apriori_python 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/50K10.txt /home/cesare/Projects/apriori-and-sons/result/apriori_python_50K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_python_50K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_spark_25K40_10 apriori_spark 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/25K40.txt /home/cesare/Projects/apriori-and-sons/result/apriori_spark_25K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_spark_25K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_spark_100K40_10 apriori_spark 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K40.txt /home/cesare/Projects/apriori-and-sons/result/apriori_spark_100K40_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_spark_100K40_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_spark_retail_10 apriori_spark 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/retail.txt /home/cesare/Projects/apriori-and-sons/result/apriori_spark_retail_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_spark_retail_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_spark_100K10_10 apriori_spark 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/100K10.txt /home/cesare/Projects/apriori-and-sons/result/apriori_spark_100K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_spark_100K10_10_logs.txt || true
python /home/cesare/Projects/apriori-and-sons/main.py runtask apriori_spark_50K10_10 apriori_spark 0.1 /home/cesare/Projects/apriori-and-sons/data/benchmark/50K10.txt /home/cesare/Projects/apriori-and-sons/result/apriori_spark_50K10_10 /home/cesare/Projects/apriori-and-sons/result/index_1688219441.csv 2>&1 | tee /home/cesare/Projects/apriori-and-sons/result/logs/apriori_spark_50K10_10_logs.txt || true
